# Site settings
author: "Saurabh Mathur"
title: Saurabh's Blog
email: saurabhmathur96@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://saurabhmathur96.github.io/blog" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
